name: videoplayar
description: A streaming video solution for your flutter app


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.10.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/videos/Butterfly-209.mp4
  - assets/videos/AppDemo01_studylist.mp4
